package com.hackathon.backend.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

/**
 * Email service for all outbound emails using HTML templates.
 * All emails are sent via Mailtrap (sandbox) during development.
 *
 * Methods:
 * - sendWelcomeEmail(to, username)           — registration confirmation
 * - sendPasswordResetEmail(to, resetLink)    — forgot-password link
 * - sendTwoFactorEmail(to, username, otp)    — 2FA OTP code
 */
@Service
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${spring.mail.username}")
    private String fromAddress;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    // ─── Public Methods ────────────────────────────────────────────────────────

    /** Sends a branded HTML welcome email on successful registration. */
    public void sendWelcomeEmail(String to, String username) {
        String subject = "Welcome to HackBase! ⚡";
        String html = buildWelcomeHtml(username, to);
        sendHtml(to, subject, html);
    }

    /** Sends a branded HTML password-reset email with a clickable reset button. */
    public void sendPasswordResetEmail(String to, String resetLink) {
        String subject = "Reset your HackBase password";
        String html = buildPasswordResetHtml(resetLink);
        sendHtml(to, subject, html);
    }

    /**
     * Sends a branded HTML 2FA OTP email.
     * Called from AuthService.login() when twoFactorEnabled=true.
     *
     * @param to       recipient email
     * @param username recipient username (shown in greeting)
     * @param otp      6-digit code generated by TwoFactorService (SecureRandom)
     */
    public void sendTwoFactorEmail(String to, String username, String otp) {
        String subject = "Your HackBase login code: " + otp;
        String html = buildTwoFactorHtml(username, otp);
        sendHtml(to, subject, html);
    }

    // ─── Internal send helper ─────────────────────────────────────────────────

    private void sendHtml(String to, String subject, String htmlBody) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setFrom(fromAddress);
            helper.setTo(to);
            helper.setSubject(subject);
            helper.setText(htmlBody, true); // true = isHtml
            mailSender.send(message);
        } catch (MessagingException e) {
            throw new RuntimeException("Failed to send email to " + to + ": " + e.getMessage(), e);
        }
    }

    // ─── HTML Template Builders ────────────────────────────────────────────────

    private String buildWelcomeHtml(String username, String email) {
        return "<!DOCTYPE html>" +
            "<html lang='en'><head><meta charset='UTF-8'>" +
            "<meta name='viewport' content='width=device-width,initial-scale=1'>" +
            "<title>Welcome to HackBase</title></head>" +
            "<body style='margin:0;padding:0;background:#F0F4FF;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;'>" +
            "<table width='100%' cellpadding='0' cellspacing='0' style='padding:40px 20px;'>" +
            "<tr><td align='center'>" +
            "<table width='580' cellpadding='0' cellspacing='0' style='max-width:580px;width:100%;'>" +

            // Header brand
            "<tr><td align='center' style='padding-bottom:28px;'>" +
            "<span style='font-size:26px;font-weight:800;color:#4F46E5;letter-spacing:-0.5px;'>&#9889; HackBase</span>" +
            "</td></tr>" +

            // Card
            "<tr><td style='background:#fff;border-radius:16px;padding:40px;box-shadow:0 4px 24px rgba(79,70,229,0.08);'>" +

            "<h1 style='margin:0 0 8px;font-size:22px;font-weight:700;color:#1E1B4B;'>" +
            "Welcome aboard, " + username + "! &#127881;</h1>" +
            "<p style='margin:0 0 28px;font-size:15px;line-height:1.6;color:#6B7280;'>" +
            "Your HackBase account is ready. Here's a summary of your new account:</p>" +

            // Info box
            "<div style='background:#F5F3FF;border-left:4px solid #4F46E5;border-radius:0 8px 8px 0;padding:18px 20px;margin-bottom:28px;'>" +
            "<p style='margin:0 0 6px;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.8px;color:#7C3AED;'>Account Details</p>" +
            "<p style='margin:0 0 4px;font-size:14px;color:#374151;'><strong>Username:</strong> " + username + "</p>" +
            "<p style='margin:0;font-size:14px;color:#374151;'><strong>Email:</strong> " + email + "</p>" +
            "</div>" +

            "<p style='margin:0 0 28px;font-size:15px;line-height:1.6;color:#6B7280;'>" +
            "You can now log in and start exploring all features. We're glad to have you!</p>" +

            // Tip: enable 2FA
            "<div style='background:#ECFDF5;border:1px solid #6EE7B7;border-radius:8px;padding:14px 18px;margin-bottom:28px;'>" +
            "<p style='margin:0;font-size:13px;color:#065F46;'>" +
            "&#128274; <strong>Security tip:</strong> Enable Two-Factor Authentication (2FA) in your account settings for extra protection." +
            "</p></div>" +

            "<p style='margin:24px 0 0;font-size:13px;color:#9CA3AF;border-top:1px solid #F3F4F6;padding-top:20px;'>" +
            "If you didn&rsquo;t create this account, you can safely ignore this email." +
            "</p></td></tr>" +

            // Footer
            "<tr><td align='center' style='padding-top:24px;'>" +
            "<p style='margin:0;font-size:12px;color:#9CA3AF;'>" +
            "&copy; 2026 HackBase &middot; Built with &#10084;&#65039;</p>" +
            "</td></tr>" +

            "</table></td></tr></table></body></html>";
    }

    private String buildPasswordResetHtml(String resetLink) {
        return "<!DOCTYPE html>" +
            "<html lang='en'><head><meta charset='UTF-8'>" +
            "<meta name='viewport' content='width=device-width,initial-scale=1'>" +
            "<title>Reset Your Password</title></head>" +
            "<body style='margin:0;padding:0;background:#F0F4FF;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;'>" +
            "<table width='100%' cellpadding='0' cellspacing='0' style='padding:40px 20px;'>" +
            "<tr><td align='center'>" +
            "<table width='580' cellpadding='0' cellspacing='0' style='max-width:580px;width:100%;'>" +

            // Brand
            "<tr><td align='center' style='padding-bottom:28px;'>" +
            "<span style='font-size:26px;font-weight:800;color:#4F46E5;letter-spacing:-0.5px;'>&#9889; HackBase</span>" +
            "</td></tr>" +

            // Card
            "<tr><td style='background:#fff;border-radius:16px;padding:40px;box-shadow:0 4px 24px rgba(79,70,229,0.08);'>" +

            "<div style='width:48px;height:48px;background:#FEF3C7;border-radius:12px;display:inline-flex;align-items:center;justify-content:center;margin-bottom:20px;font-size:24px;'>&#128274;</div>" +
            "<h1 style='margin:0 0 8px;font-size:22px;font-weight:700;color:#1E1B4B;'>Password Reset Request</h1>" +
            "<p style='margin:0 0 28px;font-size:15px;line-height:1.6;color:#6B7280;'>" +
            "We received a request to reset your HackBase password. Click the button below to choose a new password.</p>" +

            // CTA button
            "<table cellpadding='0' cellspacing='0' style='margin-bottom:28px;'><tr>" +
            "<td style='background:#4F46E5;border-radius:8px;'>" +
            "<a href='" + resetLink + "' target='_blank' " +
            "style='display:inline-block;padding:14px 32px;font-size:15px;font-weight:600;color:#fff;text-decoration:none;border-radius:8px;'>Reset My Password</a>" +
            "</td></tr></table>" +

            // Raw link fallback
            "<p style='margin:0 0 20px;font-size:13px;color:#9CA3AF;'>Or copy this link into your browser:</p>" +
            "<p style='margin:0 0 28px;word-break:break-all;font-size:12px;color:#4F46E5;'>" + resetLink + "</p>" +

            // Expiry warning
            "<div style='background:#FEF9C3;border:1px solid #FDE047;border-radius:8px;padding:14px 18px;margin-bottom:28px;'>" +
            "<p style='margin:0;font-size:13px;color:#713F12;'>" +
            "&#9200; This link expires in <strong>15 minutes</strong>. After that, you'll need to request a new one." +
            "</p></div>" +

            "<p style='margin:24px 0 0;font-size:13px;color:#9CA3AF;border-top:1px solid #F3F4F6;padding-top:20px;'>" +
            "If you didn&rsquo;t request a password reset, you can safely ignore this email. Your password won&rsquo;t change." +
            "</p></td></tr>" +

            "<tr><td align='center' style='padding-top:24px;'>" +
            "<p style='margin:0;font-size:12px;color:#9CA3AF;'>&copy; 2026 HackBase &middot; Built with &#10084;&#65039;</p>" +
            "</td></tr>" +

            "</table></td></tr></table></body></html>";
    }

    private String buildTwoFactorHtml(String username, String otp) {
        // Format OTP with a space in the middle for readability: "483 921"
        String otpFormatted = otp.substring(0, 3) + " " + otp.substring(3);

        return "<!DOCTYPE html>" +
            "<html lang='en'><head><meta charset='UTF-8'>" +
            "<meta name='viewport' content='width=device-width,initial-scale=1'>" +
            "<title>Your Login Code</title></head>" +
            "<body style='margin:0;padding:0;background:#F0F4FF;font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;'>" +
            "<table width='100%' cellpadding='0' cellspacing='0' style='padding:40px 20px;'>" +
            "<tr><td align='center'>" +
            "<table width='580' cellpadding='0' cellspacing='0' style='max-width:580px;width:100%;'>" +

            // Brand
            "<tr><td align='center' style='padding-bottom:28px;'>" +
            "<span style='font-size:26px;font-weight:800;color:#4F46E5;letter-spacing:-0.5px;'>&#9889; HackBase</span>" +
            "</td></tr>" +

            // Card
            "<tr><td style='background:#fff;border-radius:16px;padding:40px;box-shadow:0 4px 24px rgba(79,70,229,0.08);'>" +

            "<h1 style='margin:0 0 8px;font-size:22px;font-weight:700;color:#1E1B4B;'>Your Login Code</h1>" +
            "<p style='margin:0 0 28px;font-size:15px;line-height:1.6;color:#6B7280;'>" +
            "Hi <strong>" + username + "</strong>, use the code below to complete your login. " +
            "It&rsquo;s valid for <strong>2 minutes</strong> only.</p>" +

            // OTP display box
            "<div style='background:#F5F3FF;border:2px dashed #A78BFA;border-radius:12px;padding:28px;text-align:center;margin-bottom:28px;'>" +
            "<p style='margin:0 0 4px;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:1.5px;color:#7C3AED;'>One-Time Password</p>" +
            "<p style='margin:0;font-size:48px;font-weight:800;color:#4F46E5;letter-spacing:10px;font-family:\"Courier New\",monospace;'>" +
            otpFormatted + "</p>" +
            "</div>" +

            // Warnings
            "<div style='background:#FEF2F2;border:1px solid #FCA5A5;border-radius:8px;padding:14px 18px;margin-bottom:16px;'>" +
            "<p style='margin:0;font-size:13px;color:#991B1B;'>" +
            "&#128683; <strong>Never share this code</strong> with anyone, including HackBase support." +
            "</p></div>" +

            "<div style='background:#FEF9C3;border:1px solid #FDE047;border-radius:8px;padding:14px 18px;margin-bottom:28px;'>" +
            "<p style='margin:0;font-size:13px;color:#713F12;'>" +
            "&#9200; This code <strong>expires in 2 minutes</strong>. A new code is generated each time you log in." +
            "</p></div>" +

            "<p style='margin:0 0 8px;font-size:14px;color:#374151;'>Didn&rsquo;t request this code?</p>" +
            "<p style='margin:0;font-size:13px;color:#6B7280;'>" +
            "Someone may be trying to access your account. We recommend changing your password immediately." +
            "</p>" +

            "<p style='margin:24px 0 0;font-size:13px;color:#9CA3AF;border-top:1px solid #F3F4F6;padding-top:20px;'>" +
            "For your security, this code is single-use and will be invalidated after verification." +
            "</p></td></tr>" +

            "<tr><td align='center' style='padding-top:24px;'>" +
            "<p style='margin:0;font-size:12px;color:#9CA3AF;'>&copy; 2026 HackBase &middot; Built with &#10084;&#65039;</p>" +
            "</td></tr>" +

            "</table></td></tr></table></body></html>";
    }
}
