-- ============================================================
-- HackBase Database Schema
-- Database: hackathon_db (auto-created by Spring Boot on startup)
--
-- NOTE: Hibernate (ddl-auto=update) manages table creation/updates
-- automatically. This file is for:
--   1. Reference/documentation of the schema
--   2. Inserting dummy data for testing (run manually in MySQL Workbench)
--
-- DO NOT run CREATE TABLE here — Hibernate handles it.
-- spring.sql.init.mode=never is set in application.properties.
-- ============================================================

-- Step 1: Select the database
USE hackathon_db;

-- ============================================================
-- REFERENCE SCHEMA (DO NOT UNCOMMENT — Hibernate creates this)
-- ============================================================
-- CREATE TABLE IF NOT EXISTS users (
--     id              BIGINT AUTO_INCREMENT PRIMARY KEY,
--     username        VARCHAR(255) NOT NULL UNIQUE,
--     email           VARCHAR(255) NOT NULL UNIQUE,
--     password        VARCHAR(255) NOT NULL,
--     created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
--     reset_token     VARCHAR(255),
--     reset_token_expiry DATETIME(6)
-- );

-- ============================================================
-- DUMMY DATA FOR TESTING
-- Run this ONLY after starting Spring Boot once (so Hibernate
-- creates the users table), then paste into MySQL Workbench.
--
-- Passwords below are BCrypt hashes of "password123"
-- (generated by BCryptPasswordEncoder with strength 10)
-- ============================================================

INSERT INTO users (username, email, password, created_at) VALUES
('alice_dev',   'alice@example.com',   '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lha7', NOW()),
('bob_coder',   'bob@example.com',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lha7', NOW()),
('carol_test',  'carol@example.com',   '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lha7', NOW()),
('dave_admin',  'dave@example.com',    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lha7', NOW()),
('eve_hacker',  'eve@hackbase.io',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lha7', NOW());

-- All 5 users above have password: password123
-- You can log in via POST /api/auth/login with any of these emails + "password123"

-- ============================================================
-- VERIFY INSERTED DATA
-- ============================================================
SELECT id, username, email, created_at FROM users;
